// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatSniffingSystem.Persistence.Context;

#nullable disable

namespace RatSniffingSystem.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.BehaviorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BehaviorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeObserved")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("BehaviorLogs");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.ExperimentalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ExperimentalNotes");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.FoodIntakeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AmountInCc")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TimeGiven")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("FoodIntakeLogs");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InterventionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Odor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OdorCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Odors");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.RatWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightInGrams")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RatId");

                    b.ToTable("RatWeights");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.TransferTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewOdor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SessionToSuccess")
                        .HasColumnType("int");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TransferTests");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Trial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FirstCorrectTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrectNegative")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrectPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFalseNegative")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("bit");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetOdor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrialNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Trials");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.TrialOdor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OdorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OdorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("TrialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OdorId");

                    b.HasIndex("TrialId");

                    b.ToTable("TrialOdors");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entity.Rat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProjectTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rats");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entity.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MaterialThawedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RatId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.BehaviorLog", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("BehaviorLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.ExperimentalNote", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("Notes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.FoodIntakeLog", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("FoodIntakeLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("Interventions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.RatWeight", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Rat", "Rat")
                        .WithMany("WeightRecords")
                        .HasForeignKey("RatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rat");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.TransferTest", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("TransferTests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Trial", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Session", "Session")
                        .WithMany("Trials")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.TrialOdor", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entities.Odor", "Odor")
                        .WithMany("TrialUsages")
                        .HasForeignKey("OdorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RatSniffingSystem.Domain.Entities.Trial", "Trial")
                        .WithMany("OdorPositions")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odor");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entity.Session", b =>
                {
                    b.HasOne("RatSniffingSystem.Domain.Entity.Rat", "Rat")
                        .WithMany("Sessions")
                        .HasForeignKey("RatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatSniffingSystem.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rat");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Odor", b =>
                {
                    b.Navigation("TrialUsages");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entities.Trial", b =>
                {
                    b.Navigation("OdorPositions");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entity.Rat", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("WeightRecords");
                });

            modelBuilder.Entity("RatSniffingSystem.Domain.Entity.Session", b =>
                {
                    b.Navigation("BehaviorLogs");

                    b.Navigation("FoodIntakeLogs");

                    b.Navigation("Interventions");

                    b.Navigation("Notes");

                    b.Navigation("TransferTests");

                    b.Navigation("Trials");
                });
#pragma warning restore 612, 618
        }
    }
}
